### ISSUE TITLE
Python library import error

### ISSUE THREAD

**Issue by bloerg** [ANNetGPGPU/ANNetGPGPU#3]
**EDIT:**
Everything works well with Python3. 

The following applies to Pyhton2:

I am trying to use the ANPyNetCPU library. Building works:

```
/ > cd /var/tmp
/var/tmp > git clone https://github.com/ANNetGPGPU/ANNetGPGPU
Klone nach 'ANNetGPGPU' ...
remote: Counting objects: 1455, done.
remote: Total 1455 (delta 0), reused 0 (delta 0), pack-reused 1455
Empfange Objekte: 100% (1455/1455), 1.01 MiB | 740.00 KiB/s, Fertig.
Löse Unterschiede auf: 100% (952/952), Fertig.
Prüfe Konnektivität ... Fertig.
/var/tmp > cd ANNetGPGPU/
/var/tmp/ANNetGPGPU > sh build.sh 
-- The C compiler identification is GNU 5.3.1
-- The CXX compiler identification is GNU 5.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.10") 
-- Found BZip2: /usr/lib64/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit in /usr/lib64/libbz2.so
-- Looking for BZ2_bzCompressInit in /usr/lib64/libbz2.so - found
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- CUDA must be found before CMake looks for Thrust!
-- Found SWIG: /usr/bin/swig (found version "3.0.7") 
-- Found PythonLibs: /usr/lib64/libpython3.4m.so (found version "3.4.2") 
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found unsuitable Qt version "" from NOTFOUND
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- Configuring done
-- Generating done
-- Build files have been written to: /var/tmp/ANNetGPGPU/build
Scanning dependencies of target ANNet
[  3%] Building CXX object src/CMakeFiles/ANNet.dir/2DArray.cpp.o
[  7%] Building CXX object src/CMakeFiles/ANNet.dir/3DArray.cpp.o
[ 11%] Building CXX object src/CMakeFiles/ANNet.dir/AbsLayer.cpp.o
[ 14%] Building CXX object src/CMakeFiles/ANNet.dir/AbsNet.cpp.o
[ 18%] Building CXX object src/CMakeFiles/ANNet.dir/AbsNeuron.cpp.o
[ 22%] Building CXX object src/CMakeFiles/ANNet.dir/BPLayer.cpp.o
[ 25%] Building CXX object src/CMakeFiles/ANNet.dir/BPNet.cpp.o
[ 29%] Building CXX object src/CMakeFiles/ANNet.dir/BPNeuron.cpp.o
[ 33%] Building CXX object src/CMakeFiles/ANNet.dir/Edge.cpp.o
[ 37%] Building CXX object src/CMakeFiles/ANNet.dir/Functions.cpp.o
[ 40%] Building CXX object src/CMakeFiles/ANNet.dir/HFLayer.cpp.o
[ 44%] Building CXX object src/CMakeFiles/ANNet.dir/HFNet.cpp.o
[ 48%] Building CXX object src/CMakeFiles/ANNet.dir/HFNeuron.cpp.o
[ 51%] Building CXX object src/CMakeFiles/ANNet.dir/SOMLayer.cpp.o
[ 55%] Building CXX object src/CMakeFiles/ANNet.dir/SOMNet.cpp.o
[ 59%] Building CXX object src/CMakeFiles/ANNet.dir/SOMNeuron.cpp.o
[ 62%] Building CXX object src/CMakeFiles/ANNet.dir/TrainingSet.cpp.o
[ 66%] Linking CXX static library libANNet.a
[ 66%] Built target ANNet
[ 70%] Swig source
Scanning dependencies of target _ANPyNetCPU
[ 74%] Building CXX object src/CMakeFiles/_ANPyNetCPU.dir/PyNetCPUPYTHON_wrap.cxx.o
[ 77%] Linking CXX shared module _ANPyNetCPU.so
[ 77%] Built target _ANPyNetCPU
Scanning dependencies of target BPNetCPU
[ 81%] Building CXX object examples/misc/CMakeFiles/BPNetCPU.dir/BPNetCPU.cpp.o
[ 85%] Linking CXX executable BPNetCPU
[ 85%] Built target BPNetCPU
Scanning dependencies of target HFNet
[ 88%] Building CXX object examples/misc/CMakeFiles/HFNet.dir/HFNet.cpp.o
[ 92%] Linking CXX executable HFNet
[ 92%] Built target HFNet
Scanning dependencies of target LoadBPNet
[ 96%] Building CXX object examples/misc/CMakeFiles/LoadBPNet.dir/LoadBPNet.cpp.o
[100%] Linking CXX executable LoadBPNet
[100%] Built target LoadBPNet
/var/tmp/ANNetGPGPU >
```

The Python module seems to be built:

```
/var/tmp/ANNetGPGPU > ls -l /var/tmp/ANNetGPGPU/build/src/
insgesamt 5036
-rw-rw-r--. 1 build build   83576 15. Mär 12:08 ANPyNetCPU.py
-rwxrwxr-x. 1 build build 1901152 15. Mär 12:08 _ANPyNetCPU.so
drwxrwxr-x. 4 build build    4096 15. Mär 12:08 CMakeFiles
-rw-rw-r--. 1 build build     978 15. Mär 12:08 cmake_install.cmake
drwxrwxr-x. 2 build build    4096 15. Mär 12:08 include
-rw-rw-r--. 1 build build 1498262 15. Mär 12:08 libANNet.a
-rw-rw-r--. 1 build build   19590 15. Mär 12:08 Makefile
-rw-rw-r--. 1 build build 1634028 15. Mär 12:08 PyNetCPUPYTHON_wrap.cxx
 ```

However, loading the module in Python results in an error:

```
/var/tmp/ANNetGPGPU > cd /var/tmp/ANNetGPGPU/build/src
/var/tmp/ANNetGPGPU/build/src > python
Python 2.7.10 (default, Sep 24 2015, 17:50:09) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ANPyNetCPU
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ANPyNetCPU.py", line 34, in <module>
    _ANPyNetCPU = swig_import_helper()
  File "ANPyNetCPU.py", line 30, in swig_import_helper
    _mod = imp.load_module('_ANPyNetCPU', fp, pathname, description)
ImportError: dynamic module does not define init function (init_ANPyNetCPU)
>>> 
```

OS is:
Fedora 22, AMD64

**Comment by kgullikson88** [comment]
@bloerg  I am getting the same error in python3 with CentOS7 operating system. Did you ever figure out how to fix it?

**Comment by dgrat** [comment]
I am just looking at this error.. I noticed that it works without flaws in one of my virtual OpenSuse 13.2 machines. However, with Suse Leap I get exactly the same error as posted by you. 
Which means, at least theoretically it should work. Tried to find the issue by checking whether the entry function is in the binary library: 

```
	dgrat@linux-w0wr:~/ANNetGPGPU/build/src> nm -D _ANPyNetCPU.so | grep _ANPyNetCPU
	000000000018e4ec T PyInit__ANPyNetCPU
```

The function is there, and there is also no naming error as this shows: 

```
	from sys import version_info
	if version_info >= (2, 6, 0):
	def swig_import_helper():
		from os.path import dirname
		import imp
		fp = None
		try:
		fp, pathname, description = imp.find_module('_ANPyNetCPU', [dirname(__file__)])
		except ImportError:
		import _ANPyNetCPU
		return _ANPyNetCPU
		if fp is not None:
		try:
			_mod = imp.load_module('_ANPyNetCPU', fp, pathname, description)
		finally:
			fp.close()
		return _mod
	_ANPyNetCPU = swig_import_helper()
	del swig_import_helper
	else:
	import _ANPyNetCPU
	del version_info
	try:
```

At the moment I belive the issue is maybe compiler related, but it is not so easy to find the cause, because it does not even fail on any system and I cannot find an obvious reason.
